### ISSUE TITLE
Warnings on using unsafe CRT functions when on Windows

### ISSUE THREAD

**Issue by vladipus** [P-p-H-d/mlib#57]
I get the following warnings when compiling on windows (using Clang):
mlib/m-core.h(1519,1): warning: 'fscanf' is deprecated: This function or variable may be unsafe. Consider using fscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for...

Would it be a good idea to replace those with _s variants when compiling on Windows?

**Comment by P-p-H-d** [comment]
I don't know. There are discussion within the C comity to deprecate the full annex K (in which is defined fscanf_s) in the next C standard.  So the deprecation status of fscanf is debatable as fscanf_s may disappear before fscanf...

It is still bothersome to have such warnings...
I may able to do something by detecting if _ _STDC_LIB_EXT1_ _ is defined (this is the macro that is defined if the Annex K is supported), and provides a macro that use fscanf or fscanf_s for the simple usages. The complex use of fscan_f (as used in the JSON parser or in the string module) may be harder to support however.

**Comment by P-p-H-d** [comment]
More information on Annex K: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm

**Comment by vladipus** [comment]
I think it's quite an intrusive tactic, if you ask me, since it would propagate to the whole user's application.
I suppose, if the status of the deprecation is not decided yet, and it's still a standard on Window, supporting it would be a better way to go.

**Comment by P-p-H-d** [comment]
Well, I have several issues for an implementation:

* the \_\_STDC\_LIB\_EXT1\_\_ macro is not defined in MSVS (see https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019 How can I reliably detect that theses functions are available in a pure header?
* the Microsoft functions are not compatible with the standard. For example, for scan_f, the size parameter is an unsigned for MSVS ( https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/scanf-s-scanf-s-l-wscanf-s-wscanf-s-l?redirectedfrom=MSDN&view=vs-2019 ), a rsize\_t in the standard. And since it is a va\_arg, it is mandatory to have the right argument (See also https://stackoverflow.com/questions/372980/do-you-use-the-tr-24731-safe-functions ). How do i know which savor is available?
* some Windows compilers don't support Annex K too. I suppose it was only MSVS. But you talked about clang. Are you using MS LIB C with CLANG? And this version is compatible with MS version or with the standard?
* Is the warning for each fscanf use or only when using %s %c or %[ in fscanf? 
* What about the other I/O functions? (strcpy, memcpy, printf, ...)

**Comment by vladipus** [comment]
I have the following header code, when using a Clang:
```c
    #if __STDC_WANT_SECURE_LIB__

        _Check_return_opt_
        _CRT_STDIO_INLINE int __CRTDECL fscanf_s(
            _Inout_                        FILE*       const _Stream,
            _In_z_ _Scanf_s_format_string_ char const* const _Format,
            ...)
    #if defined _NO_CRT_STDIO_INLINE // SCANF
        ;
    #else
        {
            int _Result;
            va_list _ArgList;
            __crt_va_start(_ArgList, _Format);
            _Result = _vfscanf_s_l(_Stream, _Format, NULL, _ArgList);
            __crt_va_end(_ArgList);
            return _Result;
        }
    #endif
```
I think `__STDC_WANT_SECURE_LIB__` can be used to detect the function.

**Comment by vladipus** [comment]
Let me check the other points...

**Comment by vladipus** [comment]
The Clang headers are located here: `C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt`

**Comment by P-p-H-d** [comment]
Can you test the following example and see what warnings it generate?
Thanks

https://gist.github.com/P-p-H-d/76b00c69b1dfaf349d1e9152e6ed5a8c

**Comment by vladipus** [comment]
Sorry for the delay. I've tested your sample and this what I got on the output:
```
[main] Building folder: gt-generator test_apparatus
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/projects/gt-generator/build --config Debug --target test_apparatus -- -j 14
[build] [1/2   0% :: 0.000] Re-checking globbed directories...
[build] [1/2  50% :: 0.067] Building C object test\CMakeFiles\test_apparatus.dir\test_apparatus.c.obj
[build] FAILED: test/CMakeFiles/test_apparatus.dir/test_apparatus.c.obj 
[build] C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo  -ID:\projects\gt-generator\motor\include /DWIN32 /D_WINDOWS /W3 -Wall -Werror /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fotest\CMakeFiles\test_apparatus.dir\test_apparatus.c.obj /Fdtest\CMakeFiles\test_apparatus.dir\ -c D:\projects\gt-generator\motor\test\test_apparatus.c
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(2,9): error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]
[build] #define __STDC_WANT_LIB_EXT1__ 1
[build]         ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(36,9): error: macro is not used [-Werror,-Wunused-macros]
[build] #define m_qsort(...) qsort_s(__VA_ARGS__)
[build]         ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(40,9): error: macro is not used [-Werror,-Wunused-macros]
[build] #define m_strncpy(s1, s2, size) strncpy_s(s1, size, s2, size)
[build]         ^
[build] 3 errors generated.
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1

```

**Comment by vladipus** [comment]
This what I get *without* the `__STDC_WANT_LIB_EXT1__` definition:
```
[main] Building folder: gt-generator test_apparatus
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/projects/gt-generator/build --config Debug --target test_apparatus -- -j 14
[build] [1/2   0% :: 0.000] Re-checking globbed directories...
[build] [1/2  50% :: 0.073] Building C object test\CMakeFiles\test_apparatus.dir\test_apparatus.c.obj
[build] FAILED: test/CMakeFiles/test_apparatus.dir/test_apparatus.c.obj 
[build] C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo  -ID:\projects\gt-generator\motor\include /DWIN32 /D_WINDOWS /W3 -Wall -Werror /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fotest\CMakeFiles\test_apparatus.dir\test_apparatus.c.obj /Fdtest\CMakeFiles\test_apparatus.dir\ -c D:\projects\gt-generator\motor\test\test_apparatus.c
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(60,30): error: format string is not a string literal [-Werror,-Wformat-nonliteral]
[build]     m_vsnprintf(buffer, 256, format, args);
[build]                              ^~~~~~
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(47,36): note: expanded from macro 'm_vsnprintf'
[build] #define m_vsnprintf(...) vsnprintf(__VA_ARGS__)
[build]                                    ^~~~~~~~~~~
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(67,15): error: 'fopen' is deprecated: This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Werror,-Wdeprecated-declarations]
[build]     FILE *f = m_fopen("tmp.txt", "wt");
[build]               ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(43,22): note: expanded from macro 'm_fopen'
[build] #define m_fopen(...) fopen(__VA_ARGS__)
[build]                      ^
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h(207,20): note: 'fopen' has been explicitly marked deprecated here
[build]     _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
[build]                    ^
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(311,55): note: expanded from macro '_CRT_INSECURE_DEPRECATE'
[build]         #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
[build]                                                       ^
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(301,47): note: expanded from macro '_CRT_DEPRECATE_TEXT'
[build] #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
[build]                                               ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(74,5): error: 'fscanf' is deprecated: This function or variable may be unsafe. Consider using fscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Werror,-Wdeprecated-declarations]
[build]     m_fscanf(stdin, " %99s", m_fscanf_strarg(buffer, sizeof buffer));
[build]     ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(50,23): note: expanded from macro 'm_fscanf'
[build] #define m_fscanf(...) fscanf(__VA_ARGS__)
[build]                       ^
[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h(1196,20): note: 'fscanf' has been explicitly marked deprecated here
[build]     _Check_return_ _CRT_INSECURE_DEPRECATE(fscanf_s)
[build]                    ^
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(311,55): note: expanded from macro '_CRT_INSECURE_DEPRECATE'
[build]         #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
[build]                                                       ^
[build] C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\vcruntime.h(301,47): note: expanded from macro '_CRT_DEPRECATE_TEXT'
[build] #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
[build]                                               ^
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(46,9): error: macro is not used [-Werror,-Wunused-macros]
[build] #define m_qsort(...) qsort(__VA_ARGS__)
[build]         ^
[build] 4 errors generated.
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```

**Comment by P-p-H-d** [comment]
```
[build] D:\projects\gt-generator\motor\test\test_apparatus.c(2,9): error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]It seems that the clang community

[build] #define __STDC_WANT_LIB_https://bugs.llvm.org/show_bug.cgi?id=33852EXT1__ 1
```
This looks like a non conformity of CLANG. __STDC_WANT_LIB_EXT1__ has to be defined by the user to use the safe functions (See https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87151942 ) and this is the standard way to do. Other errors are ok.

I have found the bug report in clang about this non conformity:
https://bugs.llvm.org/show_bug.cgi?id=33852

**Comment by P-p-H-d** [comment]
This should be fixed in master.

On Windows, for MSVS compiler or compiler that targets its compatibility, and providing the user request to use Annex K (using  \_\_STDC\_WANT\_LIB\_EXT1\_\_), M\*LIB uses the *_s functions.

For clang, you can try defining \_\_STDC\_WANT\_LIB\_EXT1\_\_ in the command line (-D\_\_STDC\_WANT\_LIB\_EXT1\_\_).

**Comment by vladipus** [comment]
Thank you.
I'll check and will close the issue if everything is fine.

**Comment by vladipus** [comment]
This now triggers no warnings for me. Thank you.

**Comment by vladipus** [comment]
Seems like this one is not resolved just yet as `strcpy` is not covered yet: `[build] C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\string.h(133,1): note: 'strcpy' has been explicitly marked deprecated here
[build] __DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_1`

**Comment by vladipus** [comment]
BTW, MSVS - is an incorrect naming for VS compilers. MSVC is the standard one.

**Comment by vladipus** [comment]
Sorry, this issue is within my code.
